name: Update released
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y python3-pip && sudo pip3 install requests

      - name: Create snapcraft.yaml
        run: python generator.py

      - name: Check snapcraft.yaml exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "snapcraft.yaml"

      - name: Build snap
        if: steps.check_files.outputs.files_exists == 'true'
        uses: snapcore/action-build@v1
        id: build

      - name: Release snap
        if: steps.build.outputs.snap
        uses: snapcore/action-publish@v1.2.0
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable
