name: Update released
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y python3-pip && sudo pip3 install requests

      - name: Update snapcraft.yaml
        run: python generator.py

      - uses: snapcore/action-build@v1
        id: build

      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable