name: Update release
on:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install requests

      - name: Update snapcraft.yaml
        run: python generator.py

      - uses: snapcore/action-build@v1
        id: build

      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable